
alias ls='lsd -A'
alias vim='nvim'
alias c='clear'
alias clock="tty-clock -S -s  -c"
alias matrix="unimatrix -s 95 -u 10"
alias cc="paru -Scc"
alias cleanup="paru -Rns $(paru -Qtdg)"
alias se="sudo -e"
alias syu="paru -Syu"
alias ss="paru -Ss"
alias pss="pacman -Ss"
alias r="paru -Rns"
alias s="paru -S"
alias cfg="micro ~/.config/zsh/.zshrc"
alias cat="bat"
alias ping="prettyping"
alias nano="micro"
alias empty='sudo rm -rf ~/.local/share/Trash/files'
alias pls="sudo !!"
alias pg="ping -c 3 google.com"
alias iwc="iwctl station wlan0"
alias iwl="iwctl"
alias nt="iwc get-networks"
alias yd="yt-dlp -f 'bestvideo[height=480]+bestaudio' -S vcodec:h264,res:480,acodec:m4a"
alias ff="fastfetch"
alias pol="/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1"
alias mv="mv -iv"
alias rm="trash -v"
alias df="df -h"
alias du="du -h -d 1"
alias monkeytype="toofan"
alias rs="source ~/.config/zsh/.zshrc"
alias lsblk="lsblk | bat -l conf -p"
alias freec="free -h | bat -l cpuinfo -p"
alias sensors="sensors | bat -l cpuinfo -p"
alias up="yes | arch-update"
alias windows="sudo mount -t ntfs-3g -o rw /dev/nvme0n1p3 /mnt"
alias clock2=" tenki --timer-color green --wind disable --blink-colon"
alias wifi="sudo rfkill unblock wifi; impala"
alias egg="~/Documents/Scripts/egg.sh"
alias ratem="rate-mirrors --disable-comments-in-file --entry-country=ID --protocol=https arch --max-delay 7200 | sudo tee /etc/pacman.d/mirrorlist"
alias refm="sudo reflector --verbose --latest 10 --sort rate --save /etc/pacman.d/mirrorlist"

# python aliases
alias venv='python3 -m venv .venv && source .venv/bin/activate'
alias py="python"
alias vite="pnpm create vite@latest"
alias release="echo 0 | sudo tee /proc/sys/vm/nr_hugepages"
