export FZF_DEFAULT_OPTS="--style minimal --color 16 --layout=reverse --height 30% --preview='bat -p --color=always {}'"
export FZF_CTRL_R_OPTS="--style minimal --color 16 --info inline --no-sort --no-preview" # separate opts for history widget
export BAT_THEME_DARK="everforest"
export BAT_THEME_LIGHT="everforest"
export ZSH_HIGHLIGHT_STYLES[alias]='fg=green,bold'
export ZSH_HIGHLIGHT_STYLES[command]='fg=green,bold'
export ZSH_HIGHLIGHT_STYLES[precommand]='fg=cyan,bold'
export ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=yellow,italic'
export ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=yellow,italic'
export ZSH_AUTOSUGGEST_STRATEGY=(history completion)
